### ISSUE TITLE
[Bug]: s7-1500 NullPointerException

### ISSUE THREAD

**Issue by anganing** [apache/plc4x#1012]
### What happened?

help me,please!
i want to read s7-1500, but s null pointer exception occurred! hear is my code:
![image](https://github.com/apache/plc4x/assets/63218247/ceec7ef4-0299-4305-ab37-4515ab248e79)

the exception:
![image](https://github.com/apache/plc4x/assets/63218247/cf13b0a5-3a61-4444-aabc-93d4eca69856)

### Version

v0.10.0

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [ ] OPC-UA
- [X] S7

**Comment by hongjinlin** [comment]
Hello, is your s7-1500 a real device?

**Comment by glcj** [comment]
Hello,

1. If it is a physical equipment, check the address of the device or the CP.
2. If it is the Advanced PLCSIM, you must assign it an IP address within your subnet.
3. If it's not the advanced, standard PLCSIM, you can try [1].

1. https://nettoplcsim.sourceforge.net/

**Comment by anganing** [comment]
@hongjinlin 
no, I use snap7 server demo.
![image](https://github.com/apache/plc4x/assets/63218247/e2659c92-2da7-4ebe-bfa8-3eb0600a23ea)

**Comment by anganing** [comment]
@glcj 
i use snap7 server demo. i repalce it to NetToPLCSim, when i connect to the server:
![image](https://github.com/apache/plc4x/assets/63218247/0a9b56d1-b60b-43b0-9fbf-ff37ce63a532)

**Comment by spnettec** [comment]
try my repository. It's NettyPlcConnection bug

**Comment by anganing** [comment]
@spnettec how to use your repository?

**Comment by anganing** [comment]
@spnettec the payload is null,It's NettyPlcConnection bug?
![image](https://github.com/apache/plc4x/assets/63218247/073172c7-295a-4736-953a-6e448ee8b268)

**Comment by hongjinlin** [comment]
> @hongjinlin no, I use snap7 server demo. ![image](https://user-images.githubusercontent.com/63218247/250421335-e2659c92-2da7-4ebe-bfa8-3eb0600a23ea.png)

It seems that the snap7 server is not started successfully. Can you confirm if your 127.0.0.1:102 is listening?

**Comment by anganing** [comment]
> > @hongjinlin no, I use snap7 server demo. ![image](https://user-images.githubusercontent.com/63218247/250421335-e2659c92-2da7-4ebe-bfa8-3eb0600a23ea.png)
> 
> It seems that the snap7 server is not started successfully. Can you confirm if your 127.0.0.1:102 is listening?

yes, i sure. that is i use another tool with port 102 cause Permission denied

**Comment by hongjinlin** [comment]
> > > @hongjinlin no, I use snap7 server demo. ![image](https://user-images.githubusercontent.com/63218247/250421335-e2659c92-2da7-4ebe-bfa8-3eb0600a23ea.png)
> > 
> > 
> > It seems that the snap7 server is not started successfully. Can you confirm if your 127.0.0.1:102 is listening?
> 
> yes, i sure. that is i use another tool with port 102 cause Permission denied

Hi, I think you can use the snap7 client to determine whether the data can be read normally. Or if you just want to confirm whether the PLC4X is normally used in your scenario, you can try it with a physical device.

**Comment by anganing** [comment]
> 

thanks a lot, I found the bug: invalid resource address. I think the plc4x's docs are not enough detailed,some times bugs given
![image](https://github.com/apache/plc4x/assets/63218247/816be4a2-55c0-4852-a54f-5952be0423ba)
![image](https://github.com/apache/plc4x/assets/63218247/c08fe376-dce3-46d1-a170-1c01ec2f2315)

**Comment by sruehl** [comment]
whatever happens a NPE shouldn't occur there. @glcj any idea?

**Comment by glcj** [comment]
Hello,

I'll take note, but it must be associated with regex processing.

It can be seen that it has erroneous addresses, for security it should pre-process the PlcTags before carrying out the build and discard those that contain errors.

From that point of view it is not so unreasonable to avoid execution with error tags.

Kind regards.

**Comment by anganing** [comment]
> Hello,
> 
> I'll take note, but it must be associated with regex processing.
> 
> It can be seen that it has erroneous addresses, for security it should pre-process the PlcTags before carrying out the build and discard those that contain errors.
> 
> From that point of view it is not so unreasonable to avoid execution with error tags.
> 
> Kind regards.

Thank you very much for your help. I hope the documentation can be more detailed (with more usage examples), which can help beginners quickly use it
