### ISSUE TITLE
[Bug]: write a value to coil by modbus-tcp,respons:INVALID_DATA

### ISSUE THREAD

**Issue by anganing** [apache/plc4x#1018]
### What happened?

hello,
I use ModbusPal and Modbus Slave as a Slave.

when I write a coil value（true or 1） to slave,  response code is all INVALID_DATA.

addtionally, read coil all no problem.

hear is my code:

![image](https://github.com/apache/plc4x/assets/63218247/e7b81773-d28e-461c-94ba-f71b87b0580d)
![image](https://github.com/apache/plc4x/assets/63218247/f216665c-410c-4a13-9ba0-e77f512ce2a1)
![image](https://github.com/apache/plc4x/assets/63218247/c8ed7c2e-06d5-45b6-b01c-f0736aa5bc02)

any advice?

Respectfully.

### Version

v0.10.0

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [X] Modbus
- [ ] OPC-UA
- [ ] S7

**Comment by hutcheb** [comment]
I was able to replicate this using version 0.10.

It is fixed in the latest version 0.11 snapshot.

**Comment by spnettec** [comment]
Did you set ModbusPal to Holding registers? If i set to Holding registers i have this error. If set Coils correctly it is ok.
<img width="424" alt="image" src="https://github.com/apache/plc4x/assets/1769060/87520d0c-84e7-4e10-83a9-7535523280fe">

**Comment by anganing** [comment]
> I was able to replicate this using version 0.10.
> 
> It is fixed in the latest version 0.11 snapshot.

oh,thanks
