### ISSUE TITLE
[Feature Request]: when 0.11.0 version release???

### ISSUE THREAD

**Issue by kdxq** [apache/plc4x#1033]
### What would you like to happen?

when 0.11.0 version release???

### Programming Languages

- [ ] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [ ] OPC-UA
- [ ] S7

**Comment by chrisdutz** [comment]
when done ;-)

**Comment by splatch** [comment]
I think that we could and even should make an 0.11.0-RC1 build (or a bit late 0.11.0-2Q2023 => 2nd quarter of 2023), to tag current develop state. We found that some of unit tests we had did not cover some edge cases, so we're still prone to manual testing conducted by end users. As usual, there is some ongoing development, but if we don't do releases we leave people to same problem summarized as "use latest snapshot" and miss a feedback loop of what got broken in mean while.

**Comment by sruehl** [comment]
I really dislike those "-RC/Milestone/whatever" releases as those trigger renovate/dependabot and suggest those are normal releases as those bots/implementation don't understand that this isn't a real release. And by just releasing something it doesn't magically stabilize. E.g. we still need to fix the s7 driver in golang.

**Comment by sruehl** [comment]
Also: We always have the option to backport changes into a point release if they a urgently needed.

**Comment by sruehl** [comment]
so to wrap that up: we don't have a date for a release yet

**Comment by splatch** [comment]
> I really dislike those "-RC/Milestone/whatever" releases as those trigger renovate/dependabot and suggest those are normal releases as those bots/implementation don't understand that this isn't a real release. And by just releasing something it doesn't magically stabilize. E.g. we still need to fix the s7 driver in golang.

1. The way in which mentioned tools deal with our release is not related to issue. Reading your comment in reverse order I could understand that making no releases makes these tools happier. ;)
2. We won't stabilize things by releases, but do have a marker when things broke. With 11 months old snapshot you never know when things rotten.

I doubt if backporting a change made on a year old feature development branch (which develop in fact is) will ever succeed. It will work with minor patches, but not with new features which are based on i.e. MSpec generator updates etc.
