### ISSUE TITLE
[Bug]: opcua tag read status error

### ISSUE THREAD

**Issue by qtvbwfn** [apache/plc4x#1249]
### What happened?

UaExpert read OK, plc4x read error

![image](https://github.com/apache/plc4x/assets/5848026/b4b46410-d5c0-4149-bb9c-989c8cc090b0)

### Version

V0.10.0

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [X] OPC-UA
- [ ] S7

**Comment by splatch** [comment]
I think it could be related to string encoding, I recall there was similar issue a while ago. Please have a look on #568.

As far I can see fix for this bug should be included present in 0.11 release. Version 0.10 been released on 6th October 2022, prior discovery of linked issue.

**Comment by chrisdutz** [comment]
But that's in 0.11.0 so it seems you would need to update to v0.11.0

**Comment by qtvbwfn** [comment]
I tested it on V0.11.0 and it works fine. Thank you.  @splatch  @chrisdutz
