### ISSUE TITLE
[Bug][OPC-UA]: Can't read array of structures

### ISSUE THREAD

**Issue by alegue87** [apache/plc4x#1291]
### What happened?

Hello,

i'm trying to read an array of simple structure ( Range type ) in opcua with this query string: **ns=2;s=range;STRING**
This is a view with opcua-expert:

![Schermata del 2023-12-14 17-15-18](https://github.com/apache/plc4x/assets/11330154/6cbff2a6-5841-43fe-a4d2-8f564d7623b3)

Following the code the array of length 10 elements is present ( itemCount = 10 ) and the Range class in package org.apache.plc4x.java.opcua.readwrite is created and ready.

![Schermata del 2023-12-14 17-10-16](https://github.com/apache/plc4x/assets/11330154/6df0cd6b-50e4-4e68-ac08-1da916bb97a5)

The exception

 _Caused by: org.apache.plc4x.java.api.exceptions.PlcRuntimeException: org.apache.plc4x.java.spi.generation.ParseException: Unsupported case for discriminated type parameters [VariantType=0 arrayLengthSpecified=false]_ 

is raised when plc4x try to instantiate a builder from the identifierType ( not extracted from readBuffer)

![Schermata del 2023-12-14 17-10-36](https://github.com/apache/plc4x/assets/11330154/96026309-a67a-4e8b-ad41-ec03774fa23b)

where is the error?

thanks for any reply

### Version

v0.10.0, v0.11.0

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [X] OPC-UA
- [ ] S7

**Comment by splatch** [comment]
Hello @alegue87, thank you for reporting bug and coming with interesting case!

While I might be wrong, it looks like combination of several aspects - the custom type combined with (probably) unbounded array. Would you be able to provide a pcap capture with OPC UA packet containing this answer? I would like to see how data is encoded to check if we can detect it in any way and align to base type. The VariantType 0 is null, which is obviously not available in screen you showed.

If you have a possibility to provide prosys simulation server project I'll also be able to repeat it.

**Comment by splatch** [comment]
Hello @alegue87, can you post some wireshark capture so we can verify frame decoding? Also, please give a try to PLC4X 0.12 which was released recently.

**Comment by splatch** [comment]
Closed due to inactivity and missing input.
