### ISSUE TITLE
[Feature Request]: can you show the v0.10.0‘s docs?

### ISSUE THREAD

**Issue by anganing** [apache/plc4x#1292]
### What would you like to happen?

my project can't use java11 only 8, now i can use plc4x v0.11.0 only, but i can't find the v0.10.0's docs to how to use plc4x

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [X] OPC-UA
- [ ] S7

**Comment by chrisdutz** [comment]
This should help a bit? 
https://github.com/apache/plc4x/tree/rel/0.10/src/site/asciidoc

**Comment by chrisdutz** [comment]
Also this: https://github.com/apache/plc4x/tree/rel/0.10/plc4j/examples
