### ISSUE TITLE
[Bug] [OPC-UA]: Flaky tests 

### ISSUE THREAD

**Issue by chrisdutz** [apache/plc4x#1410]
### What happened?

In one build:
Error:  Errors: 
Error:    OpcuaPlcDriverTest.multipleThreads:512 » RejectedExecution event executor terminated

In another:
Error:  Failures: 
Error:    OpcuaSubscriptionHandleTest.subscribeTest:235 expected: <true> but was: <false>
Error:    OpcuaSubscriptionHandleTest.subscribeTest:235 expected: <true> but was: <false>
Error:  Errors: 
Error:    OpcuaSubscriptionHandleTest.subscribeTest:221 » Timeout
Error:    OpcuaSubscriptionHandleTest.subscribeTest:221 » Timeout
Error:    OpcuaSubscriptionHandleTest.subscribeTest:221 » Timeout
Error:    OpcuaSubscriptionHandleTest.subscribeTest:221 » Timeout
Error:    OpcuaSubscriptionHandleTest.subscribeTest:221 » Timeout
Error:    OpcuaSubscriptionHandleTest.subscribeTest:221 » Timeout
Error:    OpcuaSubscriptionHandleTest.subscribeTest:221 » Timeout
Error:    OpcuaSubscriptionHandleTest.subscribeTest:221 » Timeout
Error:    OpcuaSubscriptionHandleTest.subscribeTest:221 » Timeout

### Version

v0.11.0-SNAPSHOT

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [X] OPC-UA
- [ ] S7

**Comment by splatch** [comment]
Continued in #1764.
