### ISSUE TITLE
[Bug]: [ADS] Writing a List of Struct writes nothing

### ISSUE THREAD

**Issue by IsmoLeszczynski** [apache/plc4x#1509]
### What happened?

The PLC I'm developing against has a symbol of type List that contains a list of Structs, which aren't exposed as their own symbols (at least not included in the browse results when retrieving "symbols"). Reading the current value from the symbol produces the correct List of Struct results, but when I try to write an updated value back to it, the driver resolves it to an empty byte[]. This seems to be happening within `AdsProtocolLogic.serializeInternal()`, when iterating the list entries it determines each entry to be a list as well, since the same dataType is used for the child iteration as well, and the `DataItem.staticSerialize()` can't handle that.

How the tag is seen in TwinCAT:
![TwinCAT_screenshot](https://github.com/apache/plc4x/assets/156197448/f35b44f5-53b3-454f-8005-b418524c90dc)

The browsed symbol:
![TestTag](https://github.com/apache/plc4x/assets/156197448/632c3ed8-dec7-4457-ace9-caf1cd347656)

The attempted write value:
![TestValue_ListOfStruct](https://github.com/apache/plc4x/assets/156197448/37c2442d-b775-4335-9732-43008a693f43)

### Version

v0.12.0

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [X] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [ ] OPC-UA
- [ ] S7

**Comment by chrisdutz** [comment]
Could you add wireshark recordings of this? I only have 4h of work on PLC4X per week and I would want to make it as efficient as possible.

**Comment by IsmoLeszczynski** [comment]
Sure, here you go:
[ads-invalid-write-list-of-struct.zip](https://github.com/apache/plc4x/files/14956297/ads-invalid-write-list-of-struct.zip)

The capture contains the connection, browsing of symbols, reading the List-of-Struct symbol and writing back to it - the data bit in the write is completely empty.

I also created a PR(#1517) that fixed my use case, the issue seemed to only be that for Lists the children were also processed as Lists.

**Comment by IsmoLeszczynski** [comment]
And I apparently closed this by mistake, my bad.

**Comment by IsmoLeszczynski** [comment]
Closing this as the issue has been fixed with the merge of #1517
