### ISSUE TITLE
When will you be able to  implement  plc4x-go  s7/Reader parsePlcValue()?

### ISSUE THREAD

**Issue by songouku** [apache/plc4x#1569]
### What would you like to happen?

<img width="1288" alt="image" src="https://github.com/apache/plc4x/assets/35727333/a66d6288-f30e-407e-b077-8b54771a76be">

### Programming Languages

- [ ] plc4j
- [X] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [ ] OPC-UA
- [X] S7

**Comment by chrisdutz** [comment]
Well currently we have mainly two people working on PLC4Go ... that's @sruehl and me ... and I decided to stop working on PLC4X in my free time for free. The 4h/week I get by my employer are not barely enough to cover all types of PLC4X, so I'm concentrating on PLC4J ... If I get enough sponsoring on https://buymeacoffee.com/christoferu I might start working on other parts again (Not expecting that to happen any time soon based on prior experience with github-sponsors and alike) ... so I guess Sebastian is your best bet on this.
