### ISSUE TITLE
[Feature Request][MODBUS]: Build a QueryOptimizer for PLC4J Modbus

### ISSUE THREAD

**Issue by chrisdutz** [apache/plc4x#1671]
### What would you like to happen?

The modbus spec seems to provide limits for the size of packets. However in contrast to the other protocols, is this limit not related to the size of the packet, but by the number of registers/coils. 

Please refer to: https://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf, page: 11

It should be simple to implement a query-optimizer for Modbus to automatically handle this. The Siemens S7 QueryOptimizer might help with inspiration.

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [X] Modbus
- [ ] OPC-UA
- [ ] S7

**Comment by chrisdutz** [comment]
So it seems that the limitations are:

Max 2000 coils in one request (Page 11)
Max 125 registers in one request (Page 15)

**Comment by chrisdutz** [comment]
So luckily I need to implement this feature for my $job ;-) Making good progress, however I'm only going to implement this for reading ... writing would possibly open pandora's box with evil issues, which I do not want to do.

**Comment by chrisdutz** [comment]
![img_v3_02ed_6339cbe1-6087-420a-a1e5-8b4a1a69112g](https://github.com/user-attachments/assets/9929acce-8803-419d-b26b-7d692e85837e)
So this is the first rough draft ... now I gotta add a bit more of testing to everything ... but more than 10 times faster reads is quite an optimization ;-)

**Comment by glcj** [comment]
Excellent work, I will run tests, those times are excellent!

**Comment by chrisdutz** [comment]
Ok ... the changes are merged ... now I think it makes sense to wait another week for some feedback.

**Comment by chrisdutz** [comment]
Ok ... closing this now ... my colleagues haven't been complaining, so it seems to work.
