### ISSUE TITLE
Are there any plans to start preparing for the development of Mitsubishi's MC protocol features

### ISSUE THREAD

**Issue by cptjackwu** [apache/plc4x#1728]
### What would you like to happen?

111

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [ ] OPC-UA
- [ ] S7

**Comment by chrisdutz** [comment]
Nope

But if you want to put in the work of find someone to finance it's development, we'll gladly help.
