### ISSUE TITLE
[Bug]: ADS, reading array returns only 1st element

### ISSUE THREAD

**Issue by fdupont-epsilia** [apache/plc4x#1754]
### What happened?

PlcReadResponse getAllBytes/getAllIntegers with PLC4J to a Beckhoff TwinCat program :

arrayVariable AT %I* : ARRAY [1..13] OF WORD;

Returns only the 1st element.

Array has :
[11, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 13]

[11] is returned.

New issue since commit : bdd05c9e765bfca294b20b398f346b241a2e0aa3 [bdd05c9]
Date: September 8, 2024 13:14:19

### Version

0.13.0-SNAPSHOT

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [X] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [ ] OPC-UA
- [ ] S7

**Comment by chrisdutz** [comment]
The code changed in that commit only affected the browse functionality ... not sure how this should have affected the read-functionaility.

**Comment by chrisdutz** [comment]
Oh ... having a deeper look at it ... it does seem as if the changes to getPlcValueTypeForAdsDataType really do have an effect on the reading of arrays ... but I'm currently cleaning up the array handling as currently it wouldn't be possible to address an array element where the array part it not at the end. So consider me working on it.

But thinking about it ... I guess I could do a quick-fix for it.

**Comment by chrisdutz** [comment]
I whish Github would not automatically close things immediately when you commit a potential fix.

**Comment by fdupont-epsilia** [comment]
With the last commit, reading array works again. Thanks.
