### ISSUE TITLE
[Feature Request]: Failed to read a V area data from a S7-200 Smart

### ISSUE THREAD

**Issue by typhoon322** [apache/plc4x#1925]
### What would you like to happen?

Failed to read a V area data from a Simens S7-200 Smart due to the MemoryArea Enum doesn't define one, the address is like VW310 or V350.0. 
![image](https://github.com/user-attachments/assets/a97bc74d-80c6-4754-9feb-230b2e7701a1)

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [ ] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [ ] OPC-UA
- [X] S7

**Comment by tingbotan** [comment]
same question

**Comment by typhoon322** [comment]
> same question

replace “V” with "DB1.DB" , it worked well.

**Comment by chrisdutz** [comment]
Good catch:
https://www.fernhillsoftware.com/help/drivers/siemens-s7/data-address-format.html
"V Memory | Vnnnn | V is an alias for Data Block 1."
Possibly we could make the driver understand this alias ... same as the "E" and "A" (german) alternatives for Q and I

**Comment by typhoon322** [comment]
> Good catch: https://www.fernhillsoftware.com/help/drivers/siemens-s7/data-address-format.html "V Memory | Vnnnn | V is an alias for Data Block 1." Possibly we could make the driver understand this alias ... same as the "E" and "A" (german) alternatives for Q and I

thanks for sharing this, bro!

**Comment by john1337** [comment]
> ### What would you like to happen?
> Failed to read a V area data from a Simens S7-200 Smart due to the MemoryArea Enum doesn't define one, the address is like VW310 or V350.0. ![image](https://github.com/user-attachments/assets/a97bc74d-80c6-4754-9feb-230b2e7701a1)
> 
> ### Programming Languages
> * [x]  plc4j[ ]  plc4go[ ]  plc4c[ ]  plc4net
> 
> ### Protocols
> * [ ]  AB-Ethernet[ ]  ADS /AMS[ ]  BACnet/IP[ ]  CANopen[ ]  DeltaV[ ]  DF1[ ]  EtherNet/IP[ ]  Firmata[ ]  KNXnet/IP[ ]  Modbus[ ]  OPC-UA[x]  S7

in my case ,connection can't be made when using s7-200,how did you do it ,my example code 
            PlcConnection connection = PlcDriverManager.getDefault()
                    .getConnectionManager()
                    .getConnection("s7://192.16.8.249?controller-type=S7_200&transport-protocol=pniop&remote-rack"
                            + "=0&remote-slot=2");
and i am using these two following maven dependencies:
    <dependency>
      <groupId>org.apache.plc4x</groupId>
      <artifactId>plc4j-api</artifactId>
      <version>0.13.0</version>
    </dependency>
    <dependency>
         <groupId>org.apache.plc4x</groupId>
         <artifactId>plc4j-driver-s7</artifactId>
         <version>0.13.0</version>
     </dependency>

**Comment by chrisdutz** [comment]
Where did you get that "transport-protocol=pniop from? That's a setting that has never existed. Sounds like some fallback to profinet. Was this some AI made up connection string?

**Comment by bajiedewow** [comment]
> ### What would you like to happen?
> Failed to read a V area data from a Simens S7-200 Smart due to the MemoryArea Enum doesn't define one, the address is like VW310 or V350.0. ![image](https://github.com/user-attachments/assets/a97bc74d-80c6-4754-9feb-230b2e7701a1)
> 
> ### Programming Languages
> * [x]  plc4j[ ]  plc4go[ ]  plc4c[ ]  plc4net
> 
> ### Protocols
> * [ ]  AB-Ethernet[ ]  ADS /AMS[ ]  BACnet/IP[ ]  CANopen[ ]  DeltaV[ ]  DF1[ ]  EtherNet/IP[ ]  Firmata[ ]  KNXnet/IP[ ]  Modbus[ ]  OPC-UA[x]  S7

hello! how to connet 200 smart ? could you show me the connet url ? I can`t connect . thank you
