### ISSUE TITLE
Substitution of returning null-Values by throwing e.g. UnsupportedOperationException

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#582]
abstract FieldItem class holds non abstract methods that return null values - this might cause strange behavior if some of the subClasses have not overridden those methods.

It may be more intuitive that instead of returning null-values an exception is thrown to make clear that operation fails due to a specific reason 

Imported from Jira [PLC4X-63](https://issues.apache.org/jira/browse/PLC4X-63). Original Jira may contain additional context.
Reported by: timbo2k.

**Comment by chrisdutz** [comment]
The affected code has been completely rewritten since the issue was created.
