### ISSUE TITLE
Add Async API for new Connections

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#584]
Currently we only support an async API for Requests.
But as creating a new Connection is sometimes even slower it would be good to provide an additional asyc API which returns a Future<PlcConnection\> and leaves it to the Client to handle asynchronity.

Imported from Jira [PLC4X-136](https://issues.apache.org/jira/browse/PLC4X-136). Original Jira may contain additional context.
Reported by: julian.feinauer.

**Comment by chrisdutz** [comment]
Can we close this issue?

**Comment by ottlukas** [comment]
As this has been opened by @JulianFeinauer I assume yes. and close with this comment.
