### ISSUE TITLE
Add minimal idiomatic Scala API

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#585]
We want to implement an idiomatic Scala API:

- no use of Java std library types
- no use of PLC4X Java API types
- no use of exceptions, instead of that use of Either
- no use of Java futures, instead use of scala future

Imported from Jira [PLC4X-12](https://issues.apache.org/jira/browse/PLC4X-12). Original Jira may contain additional context.
Reported by: britter.

**Comment by chrisdutz** [comment]
I think it's safe to close this issue ... nobody has ever really asked about scala support.
