### ISSUE TITLE
Reading LREAL from S7 causes PlcRuntimeException

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#588]
Reading an LREAL in my demo project https://github.com/sewiendl/plc4j-demo/tree/feature/read-lreal causes the following exception:```
org.apache.plc4x.java.api.exceptions.PlcRuntimeException: Field 'LReal' could not be fetched, response
was INVALID_DATATYPE
	at org.apache.plc4x.java.base.messages.DefaultPlcReadResponse.getFieldInternal(DefaultPlcReadResponse.java:577)
	at
org.apache.plc4x.java.base.messages.DefaultPlcReadResponse.getObject(DefaultPlcReadResponse.java:81)
	at
com.example.plc4jdemo.Main.main(Main.java:39)
```
The field was added with ```
                builder.addItem("LReal", "%DB101.DBX110:LREAL");
```

Imported from Jira [PLC4X-154](https://issues.apache.org/jira/browse/PLC4X-154). Original Jira may contain additional context.
Reported by: swiendl.

**Comment by chrisdutz** [comment]
I think support for LReal has just recently been added.
