### ISSUE TITLE
The RequestTransactionManagerTest.abortTransactionFromExternally seems to be a little flaky

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#590]
The build on jenkins randomly seems to fail because of this test:

RequestTransactionManagerTest.abortTransactionFromExternally
### Stacktrace

java.lang.AssertionError at org.apache.plc4x.java.spi.optimizer.RequestTransactionManagerTest.abortTransactionFromExternally(RequestTransactionManagerTest.java:153)

 

Imported from Jira [PLC4X-171](https://issues.apache.org/jira/browse/PLC4X-171). Original Jira may contain additional context.
Reported by: cdutz.

**Comment by chrisdutz** [comment]
This test hasn't been causing any real issues ...

**Comment by chrisdutz** [comment]
Turns out it was disabled ... we should definitely fix this issue and not just disable the tests.

**Comment by sruehl** [comment]
do you have a link to when it was disabled (e.g. commit)?

**Comment by chrisdutz** [comment]
On the 07.02.2020 :-)

**Comment by chrisdutz** [comment]
a811636c4b0c17aff7caab1f825dbd94bae9fac0

**Comment by chrisdutz** [comment]
I re-enabled it, and we'll investigate it, if it starts causing problems again.
