### ISSUE TITLE
Subscription to system events.

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#594]
* This version allows the subscription to the following types of events:
MODE: Report status of PLC.
SYS: Report system events.
USR: Report user events.
ALM_S: Report ALARM_SQ,ALARM_S,ALARM_SC,ALARM_DQ,ALARM_D.
ALM_8: Report NOTIFY_8P, ALARM,ALARM_8P, NOTIFY

 * The ALM_S events are generated by the S7-300. The S7-400 PLCs support ALM_S and ALM_8.
 * S7-1200 PLCs do not have a message system.
 * It does not support messages for S7-1500. Next review.

Imported from Jira [PLC4X-183](https://issues.apache.org/jira/browse/PLC4X-183). Original Jira may contain additional context.
Reported by: cgarcia.

**Comment by chrisdutz** [comment]
@glcj Can you confirm this is now implemented? If yes, please close this issue.

**Comment by glcj** [comment]
Hello,
In PR #1400 the observations of the work team in the implementation of this feature were incorporated.

This version allows the subscription to the following types of events:
**MODE:** Report status of PLC.
**SYS:** Report system events.
**USR:** Report user events.
ALM: Report ALARM_SQ,ALARM_S,ALARM_SC,ALARM_DQ,ALARM_D,NOTIFY_8P, ALARM,ALARM_8P, NOTIFY

I am waiting for a CP 343-1 for additional testing, but I consider the issue closed
