### ISSUE TITLE
OPC UA Driver should support client certificates

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#595]
For an application we need to support Cert based Security in the OPC UA Driver.

Imported from Jira [PLC4X-185](https://issues.apache.org/jira/browse/PLC4X-185). Original Jira may contain additional context.
Reported by: jfeinauer.

**Comment by marcoantigo** [comment]
Are there any estimates on when this will be implemented?

**Comment by ottlukas** [comment]
@hutcheb looked at it in 2021: 

> For 0.9, certificates for encryption is not supported.
> For encryption, asymmetric encryption is used initially, the logic for this should work. It hasn't been tested for a while and may need some minor fixes. Once the session is established it switches to symmetric encryption. I had some trouble implementing this and couldn't get it to work properly.
> For certificate based authentication, it hasn't been implemented, only anonymous and username profiles work. However it shouldn't be too difficult to implement as all of the certificate handling logic has been implemented.

This is the current state and for the time being no Developer is actively working on that. Our focus is currently on other protocols and topics. Maybe Ben can give an update.

**Comment by hutcheb** [comment]
Hi,

Sorry, there has been no progress made since the last comment. If you are
interested in working on it, I can help you get up to speed.

Kind Regards

Ben

**Comment by chrisdutz** [comment]
@hutcheb can you confirm this issue can now be closed?

**Comment by splatch** [comment]
I believe it can be closed with work done in #1007. It covers both symetric and asymmetric encryption with client certificate retrieved from keystore.

**Comment by splatch** [comment]
Completed via #1007.
