### ISSUE TITLE
User manual. Driver-S7

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#596]
The objective of the manual is to show in detail the characteristics of the developed Driver-S7, its potential and points of improvement.
It will be done incapie in the formats of items and in the best practices to optimize the communication process with Siemens S7 PLCs.
It will end with practical examples associated with Continuous (machinery) and Batch (Processes) processes.

Imported from Jira [PLC4X-180](https://issues.apache.org/jira/browse/PLC4X-180). Original Jira may contain additional context.
Reported by: cgarcia.

**Comment by chrisdutz** [comment]
@glcj I think this issue can be closed, right? If yes, please close it.

**Comment by glcj** [comment]
Many of the driver's features are documented on the page. The update will be done directly on the website.
