### ISSUE TITLE
Request future never returns when ResponseCode not OK for Siemes S7

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#601]
When a request is made against a PLC which returns a ResponseCode other than OK the future will never complete and hang forever.

Imported from Jira [PLC4X-199](https://issues.apache.org/jira/browse/PLC4X-199). Original Jira may contain additional context.
Reported by: julian.feinauer.

**Comment by chrisdutz** [comment]
The reporter meintioned in the original jira issue, that he is no longer able to reproduce the error.
