### ISSUE TITLE
Handling of FLOAT and DOUBLE has issues with generated code

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#603]
Currently the code generation still uses the Supplier-Based reading of floating-point values. This code seems to have issues with the value "0.0", which is displayed as an extremely small floating-point value.

When switching to ReadBuffer readFloat and readDouble implementation they seem to be causing errors.

Imported from Jira [PLC4X-254](https://issues.apache.org/jira/browse/PLC4X-254). Original Jira may contain additional context.
Reported by: cdutz.

**Comment by chrisdutz** [comment]
This code has completeley been rewritten.
