### ISSUE TITLE
Implement the Fatek protocol

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#607]
It would be cool if we could implement the Fatek protocol.

Protocol Spec:

[http://fatek.com.tr/downloads/yuklemeler/Manual_2_Appendix1.pdf](http://fatek.com.tr/downloads/yuklemeler/Manual_2_Appendix1.pdf)

Open-Source Project (Apache 2.0 Licensed)

[https://github.com/s4u/jfatek](https://github.com/s4u/jfatek)

[https://www.simplify4u.org/jfatek/](https://www.simplify4u.org/jfatek/)

 

Imported from Jira [PLC4X-269](https://issues.apache.org/jira/browse/PLC4X-269). Original Jira may contain additional context.
Reported by: cdutz.

**Comment by chrisdutz** [comment]
Not going to happen any time soon.
