### ISSUE TITLE
WIthout “S7 Driver running in ACTIVE mode.” Nothing response

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#608]
[main] INFO org.apache.plc4x.java.PlcDriverManager - Instantiating new PLC Driver Manager with class loader sun.misc.Launcher$AppClassLoader@14dad5dc
[main] INFO org.apache.plc4x.java.PlcDriverManager - Registering available drivers...
[main] INFO org.apache.plc4x.java.PlcDriverManager - Registering driver for Protocol s7 (Siemens S7 (Basic))
[main] INFO org.apache.plc4x.java.transport.tcp.TcpChannelFactory - Configuring Bootstrap with Configuration\{local-rack=1, local-slot=1, remote-rack=0, remot-slot=3, pduSize=1024, maxAmqCaller=8, maxAmqCallee=8, controllerType='null'}
[nioEventLoopGroup-2-1] INFO org.apache.plc4x.java.s7.readwrite.protocol.S7ProtocolLogic - S7 Driver running in ACTIVE mode.

Imported from Jira [PLC4X-273](https://issues.apache.org/jira/browse/PLC4X-273). Original Jira may contain additional context.
Reported by: kdxq.

**Comment by chrisdutz** [comment]
It looks as if the initial issue was resolved in the JIRA ticket.
