### ISSUE TITLE
org.apache.plc4x.java.opm.OPMException: Timeout during fetching values

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#610]
When use OPM of plc4j，sometimes meet error “org.apache.plc4x.java.opm.OPMException: Timeout during fetching values”。maybe one item was got more fetche request（in different threads）at a time。

Imported from Jira [PLC4X-274](https://issues.apache.org/jira/browse/PLC4X-274). Original Jira may contain additional context.
Reported by: kdxq.

**Comment by chrisdutz** [comment]
It seems this issue was abandoned ...
