### ISSUE TITLE
Add profinet-DCP

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#613]
I found some work done towards implementing the [profinet-DCP](https://profinetuniversity.com/naming-addressing/profinet-dcp/) protocol on the  [feature/profinet branch]([https://github.com/apache/plc4x/tree/feature/profinet)].

I see that the profinet protocol is not on the develop branch anymore, was it replaced with the s7 protocol?

If someone would have the time to guide me, I could work on it to update, test, and bring this discovery feature to PLC4X.

Imported from Jira [PLC4X-286](https://issues.apache.org/jira/browse/PLC4X-286). Original Jira may contain additional context.
Reported by: adrlzr.

**Comment by chrisdutz** [comment]
Seems the reported error was not PLC4X from the chat history in Jira
