### ISSUE TITLE
[Go] [CodeGeneration] When generating code for two arrays within one type, the output is invalid

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#617]
When generating code for count-arrays a numberOfBytes variable is declared automatically. As soon as one type contains two count-arrays the second one has a compile error: "no new variables on left side of :=" ... should be a simple fix ... 

Imported from Jira [PLC4X-306](https://issues.apache.org/jira/browse/PLC4X-306). Original Jira may contain additional context.
Reported by: cdutz.

**Comment by chrisdutz** [comment]
@sruehl I think this can be closed, right?

**Comment by chrisdutz** [comment]
As bacnet-tags contains a type with two count arrays, I'll close this issue
