### ISSUE TITLE
plc4x s7 driver java for real type wirte error

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#618]
Creating a write request for real type  such as 

via addItem("value-5", "%DB1.DBD16:REAL", 12.1)

 

when execute the request, error as below: 

'ERROR org.apache.plc4x.java.s7.readwrite.types.DataTransportErrorCode - No DataTransportErrorCode for value 7'

Imported from Jira [PLC4X-308](https://issues.apache.org/jira/browse/PLC4X-308). Original Jira may contain additional context.
Reported by: lhs.

**Comment by chrisdutz** [comment]
This has thoroughly been tested and should be fixed in the current version (not yet released)
