### ISSUE TITLE
OPCUA response code and details are not reported in PLC response code

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#621]
the attached screenshot shows an OPCUA response code as it is received by the underlying milo client, but the OPCUA driver reports only NOT_FOUND,
it would be great, if the underlying details are included in the OPCUA response code; the real cause for a problem is important for problem solution

Imported from Jira [PLC4X-304](https://issues.apache.org/jira/browse/PLC4X-304). Original Jira may contain additional context.
Reported by: torsten.uhr@sql-ag.de.

**Comment by splatch** [comment]
This is probably already solved by other commits, however there are some more updates in #1007 which do address handling of UA response codes.

**Comment by chrisdutz** [comment]
Can this be closed now @hutcheb @splatch ?

**Comment by splatch** [comment]
Completed via #1007, probably it was improved even earlier through series of fixes we had in 0.11 release.
