### ISSUE TITLE
plc4x for go language support s7 PLC?

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#622]
Dose the plc4x for go support S7 PLC ?

No register s7 driver function ?

Thanks! 

Imported from Jira [PLC4X-310](https://issues.apache.org/jira/browse/PLC4X-310). Original Jira may contain additional context.
Reported by: lhs.

**Comment by sruehl** [comment]
at the moment the integration is broken due to changes in plc4j and not porting them over to plc4go
