### ISSUE TITLE
Maven Precondition Check fails on M1 Mac

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#630]
I have libpcap installed (via brew install libpcap) but when I trigger the maven build the precondition check fails and reports

 
```

[INFO] --- groovy-maven-plugin:2.1.1:execute (prerequisite-check) @ plc4x-parent ---
Detected OS:
  mac
Detected Arch: x86_64Detecting Java version:    17.0.1         OK
Detecting Git version:    
2.30.1         OK
Detecting LibPcap version: missing

```

My System is a M1 Mac, if that helps using macOS Monterey 12.0.1.

Imported from Jira [PLC4X-332](https://issues.apache.org/jira/browse/PLC4X-332). Original Jira may contain additional context.
Reported by: jfeinauer.

**Comment by chrisdutz** [comment]
Builds on M1 and M2 seem to be working nicely.
