### ISSUE TITLE
OPCUA tests don't run on aarch64

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#632]
When running on aarch64 the tests interfere with each other and blocking a infinite amount of time. Currently those a disabled for aarch64

(Seems like there is missing cleanup somewhere)

Imported from Jira [PLC4X-330](https://issues.apache.org/jira/browse/PLC4X-330). Original Jira may contain additional context.
Reported by: sruehl.

**Comment by chrisdutz** [comment]
Well it seems the test are actually running on M1 an M2
