### ISSUE TITLE
modbus connection causes memory leak

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#636]
Note: The version is 0.9.1.

1. The document (here)[https://plc4x.apache.org/users/protocols/modbus.html](https://plc4x.apache.org/users/protocols/modbus.html) seems wrong. It tells me the connection string format is: "modbus-tcp:tcp://127.0.0.1:502", but my test code throws exception saying no driver until I change it to "modbus://127.0.0.1".

2. My test code writes (or reads) some value via modbus tcp every 1 second, using short tcp connection (open and close every time). The memory increases every second until out-of-memory. In process monitor I find the thread count increases 1 every time the connection opens, but never releases, althought I consider the `try-block` shall closes it automatically. In fact, I see it calls `connection.close` after the `try-block`.

Test code:

```

        while (true) {
            String connectionString = "modbus://127.0.0.1";
            try
(PlcConnection plcConnection = new PlcDriverManager().getConnection(connectionString)) {
         
      PlcWriteRequest.Builder builder = plcConnection.writeRequestBuilder();
                builder.addItem("value-1",
"holding-register:1:DINT", 30000);
                builder.addItem("value-2", "holding-register:3:REAL",
3.14);
                PlcWriteRequest writeRequest = builder.build();
                PlcWriteResponse
response = writeRequest.execute().get();
                
                for (String fieldName :
response.getFieldNames()) {
                    if(response.getResponseCode(fieldName) == PlcResponseCode.OK)
{
                        System.out.println("Value[" + fieldName + "]: updated");
               
    }

                    // Something went wrong, to output an error message instead.
         
          else {
                        System.out.println("Error[" + fieldName + "]: " + response.getResponseCode(fieldName).name());
                    
					}
                }
                System.out.println("done");
     
      }
            Thread.sleep(1000);
        }

```

It shows the connection is not cleaned properly.

I see it's more efficient to do this using long tcp connection (reuse 1 connection or use a pool). But short tcp connection should also work.

Imported from Jira [PLC4X-339](https://issues.apache.org/jira/browse/PLC4X-339). Original Jira may contain additional context.
Reported by: liangjian.

**Comment by chrisdutz** [comment]
It seems this is still an issue. I created this little program:
`
package org.apache.plc4x.java.modbus;

import org.apache.plc4x.java.api.PlcConnection;
import org.apache.plc4x.java.api.PlcDriverManager;
import org.apache.plc4x.java.api.messages.PlcWriteRequest;
import org.apache.plc4x.java.api.messages.PlcWriteResponse;
import org.apache.plc4x.java.api.types.PlcResponseCode;
import org.apache.plc4x.java.spi.values.PlcDINT;
import org.apache.plc4x.java.spi.values.PlcREAL;

public class ManualTest {

    public static void main(String[] args) throws Exception {
        while (true) {
            String connectionString = "modbus-tcp://192.168.23.30";
            try (PlcConnection plcConnection = PlcDriverManager.getDefault().getConnectionManager().getConnection(connectionString)) {
                PlcWriteRequest.Builder builder = plcConnection.writeRequestBuilder();
                builder.addTagAddress("value-1","holding-register:14:DINT",new PlcDINT(-242442424));
                builder.addTagAddress("value-2","holding-register:26:REAL",new PlcREAL(3.141593F));
                PlcWriteRequest writeRequest = builder.build();
                PlcWriteResponse response = writeRequest.execute().get();
                for (String fieldName :
                    response.getTagNames()) {
                    if(response.getResponseCode(fieldName) == PlcResponseCode.OK) {
                        System.out.println("Value[" + fieldName + "]: updated");
                    } else {
                        System.out.println("Error[" + fieldName + "]: " + response.getResponseCode(fieldName).name());
                    }
                }
                System.out.println("done");
            }
        }
    }
}
`
And I can see a constantly increasing number of open threads.
![Bildschirmfoto 2024-02-06 um 11 24 06](https://github.com/apache/plc4x/assets/651105/9fc1c0f3-ac21-49da-8b5f-f2ce80cecac1)
