### ISSUE TITLE
Nifi with OPC UA don't perform

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#638]
Hi All,

We try to use the OPC UA driver through Nifi but the parsing/split of the address in Nifi don't match the PATTERN in class OpcuaField.

We use the 0.9.1 version not available in affect verision list.

Imported from Jira [PLC4X-340](https://issues.apache.org/jira/browse/PLC4X-340). Original Jira may contain additional context.
Reported by: gvincebzh.

**Comment by LaManoServida** [comment]
This has been fixed in version 0.10, as dynamic properties for each resource have been added. Please consider closing this issue.
