### ISSUE TITLE
pvs-studio report

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#645]
||Date:|10/16/22 12:00:11|
||PVS-Studio Version:|7.21.64848.1|
||Total Warnings (GA):|215|

https://www.fly-server.ru/pvs-studio/java-plc4x/

Imported from Jira [PLC4X-356](https://issues.apache.org/jira/browse/PLC4X-356). Original Jira may contain additional context.
Reported by: pavel-pimenov.

**Comment by chrisdutz** [comment]
This analysis seems to be 2,5 years old ... we should probably just pay attention to Sonarcloud, which is reporting the same things.
