### ISSUE TITLE
Unsuported transport javacan/socketcan/virtualcan/

### ISSUE THREAD

**Issue by ottlukas** [apache/plc4x#647]
(Linux) When I try to connect the can device, the default javacan, socketcan, and can transmissions all prompt that they are not supported. But I can use the example of s7 normally. I don't know where the problem makes unsupported transport socketscan.

!image-2022-10-11-10-15-00-405.png!

!image-2022-10-11-10-15-43-100.png!

!image-2022-10-11-10-16-25-869.png!

 

Imported from Jira [PLC4X-355](https://issues.apache.org/jira/browse/PLC4X-355). Original Jira may contain additional context.
Reported by: 466787806.

**Comment by splatch** [comment]
Issue was solved by user after adjusting its project dependencies.
