### ISSUE TITLE
[ADS] The encoding used for strings is incorrect

### ISSUE THREAD

**Issue by inosik** [apache/plc4x#703]
I noticed that PLC4X uses UTF-8 encoding to read/write strings to ADS devices. According to [Beckhoffs documentation](https://infosys.beckhoff.com/content/1033/tc3_plc_intro/2529327243.html?id=4470464088993876920), the correct encoding for `STRING` variables is Windows-1252. I created a demo program in TwinCAT 3, with a string value being set to the Euro-sign:

![VirtualBoxVM_2022-12-07_11-23-16](https://user-images.githubusercontent.com/11393003/208423591-6e78d420-1934-4c9a-8a74-9aa8c90fedc2.png)

![VirtualBoxVM_2022-12-07_11-24-45](https://user-images.githubusercontent.com/11393003/208423644-949f798e-7b2f-4b41-a85e-1a202cfe0be2.png)

_Note: `BinaryString8` is a union type, consisting of a string and a byte array, which allows me to see the binary data representing the string. For comparison, there's also a version with a `WSTRING`, which is encoded using UTF-16._

As you can see, the Euro-sign is encoded as 128 (`0x80`), while [in UTF-8 it should be `0xe282ac`](https://www.fileformat.info/info/unicode/char/20ac/index.htm).

**Comment by chrisdutz** [comment]
Should be pretty simple to change ... thanks for reporting this. Would you be willing to provide a Pull-Request with a fix?

**Comment by inosik** [comment]
Sure, I‘d be happy to fix this!

**Comment by chrisdutz** [comment]
I guess you should probably have a look at the ads.mspec document in /protocols/ads ... there find the DataItem definition and update the encoding of the types.

However you probably need to add support for the encoding to the org.apache.plc4x.java.spi.generation.ReadBufferByteBased (readString) and it's counterpart org.apache.plc4x.java.spi.generation.WriteBufferByteBased (writeString) ... if you want (don't have to) ... we've got the same concept for PLC4C (plc4c/spi/src/read_buffer.c and plc4c/spi/src/write_buffer.c) and PLC4Go (plc4go/spi/utils/ReadBufferByteBased.go and plc4go/spi/utils/WriteBufferByteBased.go)

**Comment by chrisdutz** [comment]
So is there any progress on this issue?

**Comment by inosik** [comment]
Sorry for the silence, I didn't come around setting up a Java dev environment yet. But I see that you recently fixed this, so I guess this issue can be closed 👍
