### ISSUE TITLE
[Bug]: plc4j - EtherNet/IP - Cannot establish connection with PLC.

### ISSUE THREAD

**Issue by crdomatica** [apache/plc4x#845]
### What happened?

First of all, thank you for this project. It has been very useful for us. 

Using the latest version of plc4j (v0.10.0), we are not being able to establish a connection to an EtherNet/IP PLC, but using the previous version of plc4j (v0.9.1) all went well with the connection to the same EtherNet/IP PLC.

Below we share the log from PLC4j.

[log-plc4j-v0.10.0.log](https://github.com/apache/plc4x/files/10979262/log-plc4j-v0.10.0.log)

Thank you.

### Version

v0.10.0

### Programming Languages

- [X] plc4j
- [ ] plc4go
- [ ] plc4c
- [ ] plc4net

### Protocols

- [ ] AB-Ethernet
- [ ] ADS /AMS
- [ ] BACnet/IP
- [ ] CANopen
- [ ] DeltaV
- [ ] DF1
- [X] EtherNet/IP
- [ ] Firmata
- [ ] KNXnet/IP
- [ ] Modbus
- [ ] OPC-UA
- [ ] S7

**Comment by chrisdutz** [comment]
Hi,

I think this will probably be related to some major changes we merged in recently, that were supposed to increase the functionality of the EIP driver.

Seems we might be needing a little more work on that.

Would you be so kind and tell us a little bit more about the type of device you're trying to talk to? And a wireshark recording would be perfect. 

We might need one or two extra round, but it's definitely not supposed to break existing implementations.

**Comment by chrisdutz** [comment]
And please excuse me ... you said in 0.9.0 it worked and in 0.10.0 it didn't ... well the changes I referred to were actually in 0.11.0-SNAPSHOT so they couldn't have any impact on 0.10.0 ... but still ... please provide the information I requested so we can have a look.

**Comment by crdomatica** [comment]
Hi,

Thank you for your response.
The PLC we are trying to connect is a ControlLogix from Allen Bradley. I Am not sure on the exact model.
Attached I share the captures using the two versions of PLC4j on the same device.

[Wireshark Captures.zip](https://github.com/apache/plc4x/files/11016796/Wireshark.Captures.zip)

Thanks.

**Comment by chrisdutz** [comment]
Oh ... that's a fortunate coincidence ... It happens that we just recently added a PR from @hutcheb that promisses to add direct support for Allen Bradley EIP devices. While I'm having a look at the captures, could you please give the 0.11.0-SNAPSHOT version a go?

**Comment by chrisdutz** [comment]
Today I got my CompactLogix working with a real program and ran into issues with PLC4J EIP driver ... however I adjusted our mspec for EIP and with these changes I was successfully able to read and write to my controller.

Could you please check again with the latest version (SNAPSHOT)?

**Comment by chrisdutz** [comment]
Could you please confirm if this issue is solved or not?

**Comment by chrisdutz** [comment]
Closing this issue as we think it's resolved but the reporter simply failed to confirm
