### ISSUE TITLE
PLC4X Discussion

### ISSUE THREAD

**Issue by maneetgoyal** [apache/plc4x#943]
Hi All,

 - [x] In one of the [FeatherCast talks](https://www.youtube.com/watch?v=dWTwgdCxIx0), Chris talked about PLC4x for TypeScript. Is the project active? 

- [x] If the TypeScript version isn't active, is there any plans to start it? How can one contribute to it either in terms of time or money?

- [x] Is the [Help Wanted](https://github.com/apache/plc4x/wiki/Help-Wanted) Wiki still up to date? 

<img width="789" alt="Screenshot 2023-05-14 at 10 38 21 AM" src="https://github.com/apache/plc4x/assets/25290212/aadb759d-5e4f-4727-a96e-20e3df15aae1">

- [x] Also, planning to use PLC4x in some industrial applications and confused between deciding PLC4Java v/s PLC4Go. Any suggestions which one is more mature or are they at par?

- [x] Is the following [table](https://plc4x.apache.org/users/protocols/index.html) up to date?

<img width="1237" alt="Screenshot 2023-05-14 at 10 33 32 AM" src="https://github.com/apache/plc4x/assets/25290212/bbc5a98c-efe2-4460-939d-35fe9f1f1a7d">

**Comment by ottlukas** [comment]
Hi @maneetgoyal

Thank you for opening this dicussion thread.

Welcome to the PLC4X Project!

You find you questions answered below.

Feel free to also check-out our mailinglist. :-)

[Project Mailing Lists](https://plc4x.apache.org/mailing-lists.html)

> * [x] In one of the [FeatherCast talks](https://www.youtube.com/watch?v=dWTwgdCxIx0), Chris talked about PLC4x for TypeScript. Is the project active?
- No this project is not active and has not been started yet. But we as PLC4X Community are happy to support developers aiming to implement.
> * [x]  If the TypeScript version isn't active, is there any plans to start it? How can one contribute to it either in terms of time or money?
- For the time beeing mainly developer willing to put time into it and get TypeScript started as a supported language.
> * [x]  Is the [Help Wanted](https://github.com/apache/plc4x/wiki/Help-Wanted) Wiki still up to date?
- Yes it it is still up to date - We are currently investigating into Multiconnection support in a more generic way. We started some specific one in Java for S7 protocol. Check-out our mailing list as well where we discuss these kind of things.
> 
> * [x]  Also, planning to use PLC4x in some industrial applications and confused between deciding PLC4Java v/s PLC4Go. Any suggestions which one is more mature or are they at par?
- For Industrial applications we are currently recommending to use PLC4Java as this is the most mature one. PLC4Go is quite close but not at par (especially for S7, but we are working on it -> See Multiconnection discussion)
> * [x]   Is the following [table](https://plc4x.apache.org/users/protocols/index.html) up to date?
- Yes and we have another one on our confluence site: [Drivers and their Transports/Protocols](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=255069989)
